### ISSUE TITLE
Misnamed files?

### ISSUE THREAD

**Issue by JetForMe** [brokenhandsio/steampress-fluent-mysql#2]
It seems files are named for their Postgres counterparts, e.g.:

https://github.com/brokenhandsio/steampress-fluent-mysql/blob/master/Sources/SteampressFluentMysql/Repositories/FluentPostgresPostRepository.swift

The contents are for MySQL.

**Comment by 0xTim** [comment]
Oops! Definitely not a copy paste error.... Thanks for reporting!

**Comment by 0xTim** [comment]
This has been released in [1.0.1](https://github.com/brokenhandsio/steampress-fluent-mysql/releases/tag/1.0.1)
